seeds:
  - Setting:
      id: 1
      name: "start_date"
      value: "2021-11-21 20:30:00"
  - Setting:
      id: 2
      name: "end_date"
      value: "2021-11-25 20:30:00"
  - Setting:
      id: 3
      name: "event_title"
      value: "Driven.t"
  - Setting:
      id: 4
      name: "background_image"
      value: "linear-gradient(to right, #FA4098, #FFD77F)"
  - Setting:
      id: 5
      name: "logo_image"
      value: "https://driveneducation.com.br/wp-content/uploads/2021/07/logo-footer.svg"
  - TicketType:
      id: 1
      name: "Presencial"
      price: 250.00
      hotelPrice: 350.00
  - TicketType:
      id: 2
      name: "Presencial"
      price: 250.00
      hotelPrice: 0
  - TicketType:
      id: 3
      name: "Online"
      price: 100.00
